2024-11-21 21:52:23,135 - MainThread - sqlmesh.core.dialect - WARNING - 'CREATE ROLE IF NOT EXISTS sqlmesh' could not be semantically understood as it contains unsupported syntax, SQLMesh will treat the command as is. Note that any references to the model's underlying physical table can't be resolved in this case, consider using Jinja as explained here https://sqlmesh.readthedocs.io/en/stable/concepts/macros/macro_variables/#audit-only-variables (dialect.py:323)
2024-11-21 21:52:23,137 - MainThread - sqlmesh.core.dialect - WARNING - 'GRANT USAGE ON FUTURE SCHEMAS IN DATABASE demo_db TO ROLE sqlmesh' could not be semantically understood as it contains unsupported syntax, SQLMesh will treat the command as is. Note that any references to the model's underlying physical table can't be resolved in this case, consider using Jinja as explained here https://sqlmesh.readthedocs.io/en/stable/concepts/macros/macro_variables/#audit-only-variables (dialect.py:323)
2024-11-21 21:52:23,184 - MainThread - sqlmesh.core.dialect - WARNING - 'GRANT CREATE TABLE ON FUTURE SCHEMAS IN DATABASE demo_db TO ROLE sqlmesh' could not be semantically understood as it contains unsupported syntax, SQLMesh will treat the command as is. Note that any references to the model's underlying physical table can't be resolved in this case, consider using Jinja as explained here https://sqlmesh.readthedocs.io/en/stable/concepts/macros/macro_variables/#audit-only-variables (dialect.py:323)
2024-11-21 21:52:23,193 - MainThread - sqlmesh.core.dialect - WARNING - 'GRANT CREATE VIEW ON FUTURE SCHEMAS IN DATABASE demo_db TO ROLE sqlmesh' could not be semantically understood as it contains unsupported syntax, SQLMesh will treat the command as is. Note that any references to the model's underlying physical table can't be resolved in this case, consider using Jinja as explained here https://sqlmesh.readthedocs.io/en/stable/concepts/macros/macro_variables/#audit-only-variables (dialect.py:323)
2024-11-21 21:52:23,195 - MainThread - sqlmesh.core.dialect - WARNING - 'GRANT SELECT, INSERT, TRUNCATE, UPDATE, DELETE ON FUTURE TABLES IN DATABASE demo_db TO ROLE sqlmesh' could not be semantically understood as it contains unsupported syntax, SQLMesh will treat the command as is. Note that any references to the model's underlying physical table can't be resolved in this case, consider using Jinja as explained here https://sqlmesh.readthedocs.io/en/stable/concepts/macros/macro_variables/#audit-only-variables (dialect.py:323)
2024-11-21 21:52:23,197 - MainThread - sqlmesh.core.dialect - WARNING - 'GRANT REFERENCES, SELECT ON FUTURE VIEWS IN DATABASE demo_db TO ROLE sqlmesh' could not be semantically understood as it contains unsupported syntax, SQLMesh will treat the command as is. Note that any references to the model's underlying physical table can't be resolved in this case, consider using Jinja as explained here https://sqlmesh.readthedocs.io/en/stable/concepts/macros/macro_variables/#audit-only-variables (dialect.py:323)
2024-11-21 21:52:23,199 - MainThread - sqlmesh.core.dialect - WARNING - 'GRANT ROLE sqlmesh TO USER demo_user' could not be semantically understood as it contains unsupported syntax, SQLMesh will treat the command as is. Note that any references to the model's underlying physical table can't be resolved in this case, consider using Jinja as explained here https://sqlmesh.readthedocs.io/en/stable/concepts/macros/macro_variables/#audit-only-variables (dialect.py:323)
2024-11-21 21:52:24,866 - MainThread - sqlmesh.core.config.connection - INFO - Creating new DuckDB adapter for in-memory database (connection.py:325)
2024-11-21 21:52:25,010 - MainThread - sqlmesh.core.config.scheduler - WARNING - The snowflake engine is not recommended for storing SQLMesh state in production deployments. Please see https://sqlmesh.readthedocs.io/en/stable/guides/configuration/#state-connection for a list of recommended engines and more information. (scheduler.py:94)
2024-11-21 21:52:25,031 - MainThread - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.12.3, Python Version: 3.10.2, Platform: Windows-10-10.0.19045-SP0 (connection.py:414)
2024-11-21 21:52:25,032 - MainThread - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1197)
2024-11-21 21:52:25,033 - MainThread - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1278)
2024-11-21 21:52:27,594 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 3 (cursor.py:1166)
2024-11-21 21:52:27,782 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:28,085 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:28,232 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:28,389 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 3 (cursor.py:1166)
2024-11-21 21:52:28,582 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:28,752 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:28,889 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:29,181 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:29,369 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:29,672 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 9 (cursor.py:1166)
2024-11-21 21:52:29,881 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:30,181 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 9 (cursor.py:1166)
2024-11-21 21:52:30,381 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:30,682 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 0 (cursor.py:1166)
2024-11-21 21:52:30,879 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:31,079 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:31,279 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:31,421 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:31,679 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:31,879 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:32,078 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:34,325 - ThreadPoolExecutor-9_0 - sqlmesh.core.snapshot.evaluator - INFO - Listing data objects in schema NB_DEMOS.sqlmesh__SQLMESH_EXAMPLE (evaluator.py:282)
2024-11-21 21:52:34,326 - ThreadPoolExecutor-9_0 - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.12.3, Python Version: 3.10.2, Platform: Windows-10-10.0.19045-SP0 (connection.py:414)
2024-11-21 21:52:34,326 - ThreadPoolExecutor-9_0 - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1197)
2024-11-21 21:52:34,326 - ThreadPoolExecutor-9_0 - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1278)
2024-11-21 21:52:35,812 - ThreadPoolExecutor-9_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: SELECT CURRENT_DATABASE() (base.py:2062)
2024-11-21 21:52:35,980 - ThreadPoolExecutor-9_0 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:36,180 - ThreadPoolExecutor-9_0 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:36,181 - ThreadPoolExecutor-9_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: SELECT CURRENT_DATABASE() (base.py:2062)
2024-11-21 21:52:36,380 - ThreadPoolExecutor-9_0 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:36,518 - ThreadPoolExecutor-9_0 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:36,533 - ThreadPoolExecutor-9_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: SELECT DISTINCT "TABLE_CATALOG" AS "catalog", "TABLE_NAME" AS "name", "TABLE_SCHEMA" AS "schema_name", CASE WHEN "TABLE_TYPE" = 'BASE TABLE' AND "IS_DYNAMIC" = 'YES' THEN 'MANAGED_TABLE' WHEN "TABLE_TYPE" = 'BASE TABLE' THEN 'TABLE' WHEN "TABLE_TYPE" = 'TEMPORARY TABLE' THEN 'TABLE' WHEN "TABLE_TYPE" = 'LOCAL TEMPORARY' THEN 'TABLE' WHEN "TABLE_TYPE" = 'EXTERNAL TABLE' THEN 'TABLE' WHEN "TABLE_TYPE" = 'EVENT TABLE' THEN 'TABLE' WHEN "TABLE_TYPE" = 'VIEW' THEN 'VIEW' WHEN "TABLE_TYPE" = 'MATERIALIZED VIEW' THEN 'MATERIALIZED_VIEW' ELSE "TABLE_TYPE" END AS "type", "CLUSTERING_KEY" AS "clustering_key" FROM "NB_DEMOS"."INFORMATION_SCHEMA"."TABLES" WHERE "TABLE_SCHEMA" = 'sqlmesh__SQLMESH_EXAMPLE' AND "TABLE_NAME" IN ('SQLMESH_EXAMPLE__GRANT_MODEL__3436818778', 'SQLMESH_EXAMPLE__SEED_MODEL__371811167') (base.py:2062)
2024-11-21 21:52:37,383 - ThreadPoolExecutor-9_0 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:37,581 - ThreadPoolExecutor-9_0 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:37,632 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:789)
2024-11-21 21:52:37,797 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:795)
2024-11-21 21:52:37,927 - MainThread - sqlmesh.core.snapshot.evaluator - INFO - Creating schema 'NB_DEMOS.sqlmesh__SQLMESH_EXAMPLE' (evaluator.py:906)
2024-11-21 21:52:37,928 - MainThread - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.12.3, Python Version: 3.10.2, Platform: Windows-10-10.0.19045-SP0 (connection.py:414)
2024-11-21 21:52:37,928 - MainThread - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1197)
2024-11-21 21:52:37,928 - MainThread - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1278)
2024-11-21 21:52:39,679 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE SCHEMA IF NOT EXISTS "NB_DEMOS"."sqlmesh__SQLMESH_EXAMPLE" (base.py:2062)
2024-11-21 21:52:39,879 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:40,078 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:40,079 - ThreadPoolExecutor-13_0 - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.12.3, Python Version: 3.10.2, Platform: Windows-10-10.0.19045-SP0 (connection.py:414)
2024-11-21 21:52:40,080 - ThreadPoolExecutor-13_0 - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1197)
2024-11-21 21:52:40,080 - ThreadPoolExecutor-13_0 - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1278)
2024-11-21 21:52:41,693 - ThreadPoolExecutor-13_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: USE ROLE "ACCOUNTADMIN" (base.py:2062)
2024-11-21 21:52:41,883 - ThreadPoolExecutor-13_0 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:41,884 - ThreadPoolExecutor-13_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE ROLE IF NOT EXISTS sqlmesh (base.py:2062)
2024-11-21 21:52:42,085 - ThreadPoolExecutor-13_0 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:42,087 - ThreadPoolExecutor-13_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: CREATE DATABASE IF NOT EXISTS "DEMO_DB" (base.py:2062)
2024-11-21 21:52:42,225 - ThreadPoolExecutor-13_0 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:42,226 - ThreadPoolExecutor-13_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: GRANT USAGE ON WAREHOUSE "COMPUTE_WH" TO ROLE "SQLMESH" (base.py:2062)
2024-11-21 21:52:42,482 - ThreadPoolExecutor-13_0 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:42,484 - ThreadPoolExecutor-13_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: GRANT USAGE ON DATABASE "DEMO_DB" TO ROLE "SQLMESH" (base.py:2062)
2024-11-21 21:52:42,681 - ThreadPoolExecutor-13_0 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:42,683 - ThreadPoolExecutor-13_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: GRANT CREATE SCHEMA ON DATABASE "DEMO_DB" TO ROLE "SQLMESH" (base.py:2062)
2024-11-21 21:52:42,882 - ThreadPoolExecutor-13_0 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:42,884 - ThreadPoolExecutor-13_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: GRANT USAGE ON FUTURE SCHEMAS IN DATABASE demo_db TO ROLE sqlmesh (base.py:2062)
2024-11-21 21:52:43,080 - ThreadPoolExecutor-13_0 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:43,081 - ThreadPoolExecutor-13_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: GRANT CREATE TABLE ON FUTURE SCHEMAS IN DATABASE demo_db TO ROLE sqlmesh (base.py:2062)
2024-11-21 21:52:43,281 - ThreadPoolExecutor-13_0 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:43,282 - ThreadPoolExecutor-13_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: GRANT CREATE VIEW ON FUTURE SCHEMAS IN DATABASE demo_db TO ROLE sqlmesh (base.py:2062)
2024-11-21 21:52:43,425 - ThreadPoolExecutor-13_0 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:43,427 - ThreadPoolExecutor-13_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: GRANT SELECT, INSERT, TRUNCATE, UPDATE, DELETE ON FUTURE TABLES IN DATABASE demo_db TO ROLE sqlmesh (base.py:2062)
2024-11-21 21:52:43,677 - ThreadPoolExecutor-13_0 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:43,678 - ThreadPoolExecutor-13_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: GRANT REFERENCES, SELECT ON FUTURE VIEWS IN DATABASE demo_db TO ROLE sqlmesh (base.py:2062)
2024-11-21 21:52:43,878 - ThreadPoolExecutor-13_0 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:43,879 - ThreadPoolExecutor-13_0 - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: GRANT ROLE sqlmesh TO USER demo_user (base.py:2062)
2024-11-21 21:52:44,280 - ThreadPoolExecutor-13_0 - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 21:52:44,281 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:789)
2024-11-21 21:52:44,978 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:795)
2024-11-21 21:52:45,133 - MainThread - sqlmesh.core.context - ERROR - Apply Failure: Traceback (most recent call last):
  File "C:\Users\BASANT BORANA\Desktop\sqlmesh_demos\.env\lib\site-packages\sqlmesh\utils\concurrency.py", line 69, in _process_node
    self.fn(node)
  File "C:\Users\BASANT BORANA\Desktop\sqlmesh_demos\.env\lib\site-packages\sqlmesh\utils\concurrency.py", line 165, in <lambda>
    lambda s_id: fn(snapshots_by_id[s_id]),
  File "C:\Users\BASANT BORANA\Desktop\sqlmesh_demos\.env\lib\site-packages\sqlmesh\core\snapshot\evaluator.py", line 316, in <lambda>
    lambda s: self._create_snapshot(
  File "C:\Users\BASANT BORANA\Desktop\sqlmesh_demos\.env\lib\site-packages\sqlmesh\core\snapshot\evaluator.py", line 681, in _create_snapshot
    self.adapter.execute(snapshot.model.render_pre_statements(**pre_post_render_kwargs))
  File "C:\Users\BASANT BORANA\Desktop\sqlmesh_demos\.env\lib\site-packages\sqlmesh\core\engine_adapter\base.py", line 2059, in execute
    self._execute(sql, **kwargs)
  File "C:\Users\BASANT BORANA\Desktop\sqlmesh_demos\.env\lib\site-packages\sqlmesh\core\engine_adapter\base.py", line 2065, in _execute
    self.cursor.execute(sql, **kwargs)
  File "C:\Users\BASANT BORANA\Desktop\sqlmesh_demos\.env\lib\site-packages\snowflake\connector\cursor.py", line 1097, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "C:\Users\BASANT BORANA\Desktop\sqlmesh_demos\.env\lib\site-packages\snowflake\connector\errors.py", line 284, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "C:\Users\BASANT BORANA\Desktop\sqlmesh_demos\.env\lib\site-packages\snowflake\connector\errors.py", line 339, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "C:\Users\BASANT BORANA\Desktop\sqlmesh_demos\.env\lib\site-packages\snowflake\connector\errors.py", line 215, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002003 (02000): 01b885d5-3201-5499-000a-efc200047876: SQL compilation error:
User 'DEMO_USER' does not exist or not authorized.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\BASANT BORANA\Desktop\sqlmesh_demos\.env\lib\site-packages\sqlmesh\core\context.py", line 1370, in apply
    self._apply(plan, circuit_breaker)
  File "C:\Users\BASANT BORANA\Desktop\sqlmesh_demos\.env\lib\site-packages\sqlmesh\core\context.py", line 1919, in _apply
    self._scheduler.create_plan_evaluator(self).evaluate(
  File "C:\Users\BASANT BORANA\Desktop\sqlmesh_demos\.env\lib\site-packages\sqlmesh\core\plan\evaluator.py", line 117, in evaluate
    self._push(plan, snapshots, deployability_index_for_creation)
  File "C:\Users\BASANT BORANA\Desktop\sqlmesh_demos\.env\lib\site-packages\sqlmesh\core\plan\evaluator.py", line 230, in _push
    self.snapshot_evaluator.create(
  File "C:\Users\BASANT BORANA\Desktop\sqlmesh_demos\.env\lib\site-packages\sqlmesh\core\snapshot\evaluator.py", line 314, in create
    concurrent_apply_to_snapshots(
  File "C:\Users\BASANT BORANA\Desktop\sqlmesh_demos\.env\lib\site-packages\sqlmesh\utils\concurrency.py", line 163, in concurrent_apply_to_snapshots
    return concurrent_apply_to_dag(
  File "C:\Users\BASANT BORANA\Desktop\sqlmesh_demos\.env\lib\site-packages\sqlmesh\utils\concurrency.py", line 205, in concurrent_apply_to_dag
    ).run()
  File "C:\Users\BASANT BORANA\Desktop\sqlmesh_demos\.env\lib\site-packages\sqlmesh\utils\concurrency.py", line 64, in run
    self._finished_future.result()
  File "C:\python310\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "C:\python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
sqlmesh.utils.concurrency.NodeExecutionFailedError: Execution failed for node SnapshotId<"NB_DEMOS"."SQLMESH_EXAMPLE"."GRANT_MODEL": 3427827545>
 (context.py:1378)
2024-11-21 21:52:45,157 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:789)
2024-11-21 21:52:45,280 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:795)
2024-11-21 21:52:45,416 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:789)
2024-11-21 21:52:45,613 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:795)
2024-11-21 21:52:45,781 - MainThread - root - INFO - Shutting down the event dispatcher (dispatcher.py:159)
